---
# tasks file for jinja2_leaf
  - name: Generate Leaf Config
  
    template: src=leaf.j2 dest=roles/jinja2_leaf/files/{{inventory_hostname}}_{{multicast}}_{{rp_distribution}}_{{igp}}.cfg
    tags:
    - template
  - name: Push Leaf Config
    ios_config:
      src: roles/jinja2_leaf/files/{{inventory_hostname}}_{{multicast}}_{{rp_distribution}}_{{igp}}.cfg
      provider: "{{ nxos_provider }}"
    