---
# tasks file for jinja2_spine
  - name: Generate Spine Config

    template: src=spine.j2 dest=roles/jinja2_spine/files/{{inventory_hostname}}.cfg
    tags:
    - template
  - name: Push Spine Config
    ios_config:
      src: roles/jinja2_spine/files/{{inventory_hostname}}.cfg
      provider: "{{ nxos_provider }}"