---
# vars file for leaf
  nxos_provider:
    username: "{{ user }}"
    password: "{{ pwd }}"
    transport: nxapi
    timeout: 30
    host: "{{ ip_address }}"

  asn: 65000

  bgp_neighbors:
  - { remote_as: 65000, neighbor: 192.168.0.6, update_source: Loopback0 }
  - { remote_as: 65000, neighbor: 192.168.0.7, update_source: Loopback0 }

  rp_address: 192.168.0.100
  L3_interfaces:
  - { interface: Ethernet1/1 }
  - { interface: Ethernet1/2 }
  - { interface: loopback0 }
  - { interface: loopback1 }